// Code generated by "stringer -linecomment -output=gen_stringer.go -type=FuelType,Rate"; DO NOT EDIT.

package octopusenergy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuelTypeElectricity-0]
	_ = x[FuelTypeGas-1]
}

const _FuelType_name = "electricitygas"

var _FuelType_index = [...]uint8{0, 11, 14}

func (i FuelType) String() string {
	if i < 0 || i >= FuelType(len(_FuelType_index)-1) {
		return "FuelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FuelType_name[_FuelType_index[i]:_FuelType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RateStandingCharge-0]
	_ = x[RateStandardUnit-1]
	_ = x[RateDayUnit-2]
	_ = x[RateNightUnit-3]
}

const _Rate_name = "standing-chargesstandard-unit-ratesday-unit-ratesnight-unit-rates"

var _Rate_index = [...]uint8{0, 16, 35, 49, 65}

func (i Rate) String() string {
	if i < 0 || i >= Rate(len(_Rate_index)-1) {
		return "Rate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rate_name[_Rate_index[i]:_Rate_index[i+1]]
}
