name: tests

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

      - name: GoGoGo
        run: |
          go build ./...
          go test ./...
