name: tests

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3.5.1

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: GoGoGo
        run: |
          go mod download
          go test ./...
          go build ./...
